use_frameworks!

platform :ios, '11.0'

target 'SwiftyJSONDecoder_Example' do
  pod 'SwiftyJSONDecoder', :path => '../'

  target 'SwiftyJSONDecoder_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
